# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "tag-app"
client_id = "fddf6abe5200126e3a87396ba0bc3483"
application_url = "https://relax-judicial-june-c.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://relax-judicial-june-c.trycloudflare.com/auth/callback",
  "https://relax-judicial-june-c.trycloudflare.com/auth/shopify/callback",
  "https://relax-judicial-june-c.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teg-app.myshopify.com"
